### ISSUE TITLE
Provide denial reasons at the advertiser level and email advertiser 

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#1059]
Presently, if an advertiser is denied, no reason is given. It locks the advertiser out of the ad server.

When Ad Ops denies an advertiser, it should provide a list of reasons for the denial. This denial reason (or reasons) would be emailed to the advertiser, so they're aware of why this occurred.

Sample email:
"We cannot approve your advertising account due to the following reason(s):
[reason here]

In the future, if our policies change, we will reach out to you."

Some reasons for denials:
- Landing page is unreachable
- We cannot target your language at this time. Available languages are...
- CBD 
- THC
- Tobacco
- Vaping
- Pharmaceuticals
- Gambling
- Adult content
- Politics
- Violence
- Content targeting children
- Content targeting expecting mothers
- Other - to capture reasons we don’t have.  Once we are filling in "other" with the same reasons over time, we can turn them into default selections. 
etc.

If we save these denial reasons with the advertiser, this will also give us the opportunity to re-engage advertisers if any of the policies change.

**Comment by alekseva** [comment]
Below is what I put together in the best practices doc. A few of these are not in your list above. :
religious content, controversial figures (can be controversial celebrities, not necessarily politcal), sexist/racist/etc overtones, or images that stereotype groups, images of trauma and despair (Images for charities should feel hopeful rather than depressing). We should add "gambling" to the best practices doc btw.


----

sexualized imagery
guns, violence and gore
despair and trauma
controlled substances
political content
religious content
controversial figures
sexist/ racist/ etc overtones

**Comment by IanKrieger** [comment]
Resolved in https://github.com/brave/ads-serve/issues/3701
