### ISSUE TITLE
Provide denial reasons for creatives and email advertiser when denied with reason

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#1061]
Presently, if a creative is denied, no reason is given to the advertiser. Ad Ops must manually reach out via Zendesk and explained the reason for the denial, which is time consuming. 

When Ad Ops denies a creative, it should provide a list of reasons for the denial. This denial reason (or reasons) would be emailed to the advertiser, so they're aware of why this occurred.

Sample email:
"We cannot approve the following creative:
[creative]

Reason(s):
[reason]

Please correct the creative and re-submit for review."

Some reasons for denials:
- Creative does not contain the advertiser name in the ad.
- URL is not working
- Home page URL is not complete (loads, doesn’t explain company information)
- Company sells goods we cannot currently advertise on self-serve (adult, gambling, marijuana, political, etc.)
- We cannot run to this language at the present time.
- This links to a product we cannot currently advertise.
- “Other” - to capture reasons we don’t have, and once we find more that are similar, we can turn them into default selections. Or, we may find we’re denying advertisers that have a place in our platform, and can figure out how to best fit them in.

If we save these denial reasons with the creative, this will also give us the opportunity to re-engage advertisers if any of the policies change.

**Comment by alekseva** [comment]
"We cannot run to this language at the present time."
Maybe it's clear to advertisers, but I'm not sure what you mean by "running _to_ a language". Do you mean a region? Or that the ad cannot be in a certain language? The wording isn't clear, to me at least. 

I would also say that when client assets are denied, instead of just stating on what grounds it's denied, include a list of suggestions/ direction on what options they have to make it work. This is to encourage them to try again and alleviate any remaining confusion.

"Company sells goods we cannot currently advertise on self-serve (adult, gambling, marijuana, political, etc.)"
Include a list so that they can see identify which one may apply in their case?

There are some other reasons we may deny an ad in the best practices doc that is not mentioned here

I assume they have the option to contact a human upon receiving a denial? Some people prefer to speak with a person in a case like this to work through any issues.

**Comment by IanKrieger** [comment]
Resolved in https://github.com/brave/ads-serve/issues/3701
