### ISSUE TITLE
Add "Best Practices" to ads-help site

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#1223]
We need to add the Best Practices policy to our ads-help site, preferably under https://ads-help.brave.com/advertiser-policies/policies
or, we create a new "Guidelines" area.

Best Practices are listed here: https://brave.com/brave-ads/ad-formats/
- Add context to your headline for clarity, e.g.“Masterclass. Learn from the best."
- Use unique landing pages such as “advertiser.com/brave” to make measurement easier
- Use multiple versions of ad creative for testing
- Use a specific call to action: “Learn More,” “Try Now,” “Buy Now,” “Sign Up,” etc.
- Vary copy to appeal to different audiences or product features
- No click-bait headlines
- No claims of high returns on investments (APY/APR)
- No all-uppercase lettering
- No profanity, nudity, violence, or illicit substances
- No redirect URLS (ads must direct to your owned domain or social media)

@lukaslevert

**Comment by lukaslevert** [comment]
@murphyd we already have these individualized for each ad unit since they are slightly different for each and we have a full document of best practices for NTT:

https://ads-help.brave.com/ad-placements/brave-browser/news
https://ads-help.brave.com/ad-placements/brave-browser/notification
https://ads-help.brave.com/ad-placements/brave-browser/ntt

We can definitely update any one of these if they appear to be missing something.

**Comment by murphyd** [comment]
Ah nice, thanks!
